### ISSUE TITLE
can we have a SL CF template incl. network configuration settings ? 

### ISSUE THREAD

**Issue by flintstonecf** [cloudfoundry/bosh-softlayer-cpi-release#128]
Hi CPI team,

I believe that after the fixes that @sykesm has been proposing, it should be possible to create a template to deploy a plain CF to SL incl. network config. If thats true, can you please provide such a sample template ? 

@suhlig FYI

**Comment by sykesm** [comment]
It's more than just having the ability to use a portable IP in a manual network configuration. There are a number of things I'm running into with the current CPI that prevents an easy template from being created.

One of the major ones is the fact that the CPI uses the IP associated with a network to find an existing VM. In my opinion, this is just busted. It requires us to use a dynamic network and a manual network (with portable IPs) instead of just a manual.

Now that you need a manual and a dynamic, you can't use the existing templates from the releases to generate a working deployment because the templates assume a single `cf1` network.

**Comment by maximilien** [comment]
See responses to #117 

Also, note that all main official docs and samples for this CPI (like other CPIs) will be in bosh.io. Does not mean we cannot have docs here but I want bosh.io to be primary resource for docs, samples, and bits.

/cc @cppforlife

**Comment by maximilien** [comment]
See also #207
