### ISSUE TITLE
CPI needs to set Preconfigured in a smart way to keep backward compatibility

### ISSUE THREAD

**Issue by mattcui** [cloudfoundry/bosh-softlayer-cpi-release#302]
CPI needs to address the change in bosh agent to split DNS configuration and network configuration in two separated functions in near future, plan to make CPI be able to pass the proper value to boshagent for `Preconfigured` and maybe `DNSConfigured` based on the version of stemcell (before and after this change in bosh agent)

**Comment by edwardstudy** [comment]
About `Preconfigured` issue, we want to remove `writeResolvConf` func which SoftLayer doesn't need. Because SoftLayer currently hands over configure networks functionality(including `dns-nameservers` definition on `/etc/network/interfaces`) to bosh agent. Agent will write `/etc/network/interfaces`.

I just set preconfigured as false on `/var/vcap/bosh/settings.json` manually and restarted agent and got correct DNS records on `/etc/resolv.conf`.

I thought it makes sense and is a better solution for both. 

Currently, I am changing the code to test.

I'll raise a PR to remove `writeResolvConf` func and move `IsPreconfigured ` func to decide to skip `boot.platform.SetupNetworking(settings.Networks)`
on this section: https://github.com/cloudfoundry/bosh-agent/blob/719afe4619a86090b3240672e1cf7b56a290c0fa/agent/bootstrap.go#L98-L100.

**Comment by mattcui** [comment]
So it looks that it doesn't need a smart way to do that for keeping backward compatibility, closing this issue.
